namespace POEApi.Model
{
    public enum GemCategory
    {
        AoE,
        Attack,
        Aura,
        Bow,
        Cast,
        Chaining,
        Chaos,
        Cold,
        Curse,
        Duration,
        Fire,
        Lightning,
        Melee,
        Mine,
        Minion,
        Movement,
        Projectile,
        Spell,
        Totem,
        Trap,
        Support,
        Vaal
    }

    public enum GemCategory_RU
    {
        Область,
        Атака,
        Аура,
        Лук,
        Сотворение,
        Цепь,
        Хаос,
        Холод,
        Проклятье,
        Длится,
        Огонь,
        Молния,
        Ближний,
        Мина,
        Прислужник,
        Движение,
        Снаряд,
        Чары,
        Тотем,
        Ловушка,
        Поддержка,
        Ваал
    }
}
