namespace POEApi.Model
{
    public enum OrbType
    {
        Eternal,
        Imprint,
        Exalted,
        Divine,
        GemCutterPrism,
        Regal,
        Blessed,
        Chaos,
        Regret,
        Chisel,
        Alchemy,
        Scouring,
        Fusing,
        Chance,
        Chromatic,
        JewelersOrb,
        Alteration,
        Augmentation,
        Transmutation,
        PortalScroll,
        WisdomScroll,
        ArmourersScrap,
        GlassblowersBauble,
        BlacksmithsWhetstone,
        ScrollFragment,
        ScrollofWisdom,
        AlbinaRhoaFeather,
        AlchemyShard,
        Mirror,
        VaalOrb,
        PerandusCoin,
        Unknown
    }
}
