//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POEApi.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerTypeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerTypeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POEApi.Model.ServerTypeRes", typeof(ServerTypeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right click this item then left click a location on the ground to create the object..
        /// </summary>
        internal static string DecorationItemTypeText {
            get {
                return ResourceManager.GetString("DecorationItemTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amulet.
        /// </summary>
        internal static string GearTypeAmulet {
            get {
                return ResourceManager.GetString("GearTypeAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bascinet.
        /// </summary>
        internal static string GearTypeBascinet {
            get {
                return ResourceManager.GetString("GearTypeBascinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt.
        /// </summary>
        internal static string GearTypeBelt {
            get {
                return ResourceManager.GetString("GearTypeBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boots.
        /// </summary>
        internal static string GearTypeBoots {
            get {
                return ResourceManager.GetString("GearTypeBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgonet.
        /// </summary>
        internal static string GearTypeBurgonet {
            get {
                return ResourceManager.GetString("GearTypeBurgonet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap.
        /// </summary>
        internal static string GearTypeCap {
            get {
                return ResourceManager.GetString("GearTypeCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casque.
        /// </summary>
        internal static string GearTypeCasque {
            get {
                return ResourceManager.GetString("GearTypeCasque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Coif.
        /// </summary>
        internal static string GearTypeChainCoif {
            get {
                return ResourceManager.GetString("GearTypeChainCoif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chainmail Coif.
        /// </summary>
        internal static string GearTypeChainmailCoif {
            get {
                return ResourceManager.GetString("GearTypeChainmailCoif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circlet.
        /// </summary>
        internal static string GearTypeCirclet {
            get {
                return ResourceManager.GetString("GearTypeCirclet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown.
        /// </summary>
        internal static string GearTypeCrown {
            get {
                return ResourceManager.GetString("GearTypeCrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flask.
        /// </summary>
        internal static string GearTypeFlask {
            get {
                return ResourceManager.GetString("GearTypeFlask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauntlets.
        /// </summary>
        internal static string GearTypeGauntlets {
            get {
                return ResourceManager.GetString("GearTypeGauntlets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glove.
        /// </summary>
        internal static string GearTypeGlove {
            get {
                return ResourceManager.GetString("GearTypeGlove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greaves.
        /// </summary>
        internal static string GearTypeGreaves {
            get {
                return ResourceManager.GetString("GearTypeGreaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmet.
        /// </summary>
        internal static string GearTypeHelmet {
            get {
                return ResourceManager.GetString("GearTypeHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hood.
        /// </summary>
        internal static string GearTypeHood {
            get {
                return ResourceManager.GetString("GearTypeHood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        internal static string GearTypeMask {
            get {
                return ResourceManager.GetString("GearTypeMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitts.
        /// </summary>
        internal static string GearTypeMitts {
            get {
                return ResourceManager.GetString("GearTypeMitts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelt.
        /// </summary>
        internal static string GearTypePelt {
            get {
                return ResourceManager.GetString("GearTypePelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiver.
        /// </summary>
        internal static string GearTypeQuiver {
            get {
                return ResourceManager.GetString("GearTypeQuiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string GearTypeRing {
            get {
                return ResourceManager.GetString("GearTypeRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring Coif.
        /// </summary>
        internal static string GearTypeRingCoif {
            get {
                return ResourceManager.GetString("GearTypeRingCoif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringmail.
        /// </summary>
        internal static string GearTypeRingmail {
            get {
                return ResourceManager.GetString("GearTypeRingmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringmail Coif.
        /// </summary>
        internal static string GearTypeRingmailCoif {
            get {
                return ResourceManager.GetString("GearTypeRingmailCoif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sash.
        /// </summary>
        internal static string GearTypeSash {
            get {
                return ResourceManager.GetString("GearTypeSash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string GearTypeShoes {
            get {
                return ResourceManager.GetString("GearTypeShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippers.
        /// </summary>
        internal static string GearTypeSlippers {
            get {
                return ResourceManager.GetString("GearTypeSlippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string LevelText {
            get {
                return ResourceManager.GetString("LevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel to this Map.
        /// </summary>
        internal static string MapDescText {
            get {
                return ResourceManager.GetString("MapDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Level.
        /// </summary>
        internal static string MapLevelText {
            get {
                return ResourceManager.GetString("MapLevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string MapText {
            get {
                return ResourceManager.GetString("MapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albino Rhoa Feather.
        /// </summary>
        internal static string OrbTypeAlbinoRhoaFeather {
            get {
                return ResourceManager.GetString("OrbTypeAlbinoRhoaFeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy Shard.
        /// </summary>
        internal static string OrbTypeAlchemyShard {
            get {
                return ResourceManager.GetString("OrbTypeAlchemyShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteration.
        /// </summary>
        internal static string OrbTypeAlteration {
            get {
                return ResourceManager.GetString("OrbTypeAlteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armourer&apos;s Scrap.
        /// </summary>
        internal static string OrbTypeArmourerScrap {
            get {
                return ResourceManager.GetString("OrbTypeArmourerScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmentation.
        /// </summary>
        internal static string OrbTypeAugmentation {
            get {
                return ResourceManager.GetString("OrbTypeAugmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacksmith&apos;s Whetstone.
        /// </summary>
        internal static string OrbTypeBlacksmithWhetstone {
            get {
                return ResourceManager.GetString("OrbTypeBlacksmithWhetstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessed.
        /// </summary>
        internal static string OrbTypeBlessed {
            get {
                return ResourceManager.GetString("OrbTypeBlessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartographer.
        /// </summary>
        internal static string OrbTypeCartographer {
            get {
                return ResourceManager.GetString("OrbTypeCartographer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string OrbTypeChance {
            get {
                return ResourceManager.GetString("OrbTypeChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos.
        /// </summary>
        internal static string OrbTypeChaos {
            get {
                return ResourceManager.GetString("OrbTypeChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromatic.
        /// </summary>
        internal static string OrbTypeChromatic {
            get {
                return ResourceManager.GetString("OrbTypeChromatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divine.
        /// </summary>
        internal static string OrbTypeDivine {
            get {
                return ResourceManager.GetString("OrbTypeDivine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eternal Orb.
        /// </summary>
        internal static string OrbTypeEternalOrb {
            get {
                return ResourceManager.GetString("OrbTypeEternalOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exalted.
        /// </summary>
        internal static string OrbTypeExalted {
            get {
                return ResourceManager.GetString("OrbTypeExalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemcutter&apos;s Prism.
        /// </summary>
        internal static string OrbTypeGemcutterPrism {
            get {
                return ResourceManager.GetString("OrbTypeGemcutterPrism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glassblower.
        /// </summary>
        internal static string OrbTypeGlassblower {
            get {
                return ResourceManager.GetString("OrbTypeGlassblower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        internal static string OrbTypeImprint {
            get {
                return ResourceManager.GetString("OrbTypeImprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeweller&apos;s Orb.
        /// </summary>
        internal static string OrbTypeJewellerOrb {
            get {
                return ResourceManager.GetString("OrbTypeJewellerOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        internal static string OrbTypeMirror {
            get {
                return ResourceManager.GetString("OrbTypeMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb of Alchemy.
        /// </summary>
        internal static string OrbTypeOrbOfAlchemy {
            get {
                return ResourceManager.GetString("OrbTypeOrbOfAlchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orb of Fusing.
        /// </summary>
        internal static string OrbTypeOrbOfFusing {
            get {
                return ResourceManager.GetString("OrbTypeOrbOfFusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Scroll.
        /// </summary>
        internal static string OrbTypePortalScroll {
            get {
                return ResourceManager.GetString("OrbTypePortalScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regal.
        /// </summary>
        internal static string OrbTypeRegal {
            get {
                return ResourceManager.GetString("OrbTypeRegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regret.
        /// </summary>
        internal static string OrbTypeRegret {
            get {
                return ResourceManager.GetString("OrbTypeRegret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scouring.
        /// </summary>
        internal static string OrbTypeScouring {
            get {
                return ResourceManager.GetString("OrbTypeScouring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Fragment.
        /// </summary>
        internal static string OrbTypeScrollFragment {
            get {
                return ResourceManager.GetString("OrbTypeScrollFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll of Wisdom.
        /// </summary>
        internal static string OrbTypeScrollOfWisdom {
            get {
                return ResourceManager.GetString("OrbTypeScrollOfWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmutation.
        /// </summary>
        internal static string OrbTypeTransmutation {
            get {
                return ResourceManager.GetString("OrbTypeTransmutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaal Orb.
        /// </summary>
        internal static string OrbTypeVaalOrb {
            get {
                return ResourceManager.GetString("OrbTypeVaalOrb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string QualityText {
            get {
                return ResourceManager.GetString("QualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Size.
        /// </summary>
        internal static string StackSizeText {
            get {
                return ResourceManager.GetString("StackSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambusher.
        /// </summary>
        internal static string WeaponTypeAmbusher {
            get {
                return ResourceManager.GetString("WeaponTypeAmbusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awl.
        /// </summary>
        internal static string WeaponTypeAwl {
            get {
                return ResourceManager.GetString("WeaponTypeAwl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        internal static string WeaponTypeAxe {
            get {
                return ResourceManager.GetString("WeaponTypeAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bladed Mace.
        /// </summary>
        internal static string WeaponTypeBladedMace {
            get {
                return ResourceManager.GetString("WeaponTypeBladedMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinder.
        /// </summary>
        internal static string WeaponTypeBlinder {
            get {
                return ResourceManager.GetString("WeaponTypeBlinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Blade.
        /// </summary>
        internal static string WeaponTypeBootBlade {
            get {
                return ResourceManager.GetString("WeaponTypeBootBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        internal static string WeaponTypeBow {
            get {
                return ResourceManager.GetString("WeaponTypeBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker.
        /// </summary>
        internal static string WeaponTypeBreaker {
            get {
                return ResourceManager.GetString("WeaponTypeBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckler.
        /// </summary>
        internal static string WeaponTypeBuckler {
            get {
                return ResourceManager.GetString("WeaponTypeBuckler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chopper.
        /// </summary>
        internal static string WeaponTypeChopper {
            get {
                return ResourceManager.GetString("WeaponTypeChopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claw.
        /// </summary>
        internal static string WeaponTypeClaw {
            get {
                return ResourceManager.GetString("WeaponTypeClaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaver.
        /// </summary>
        internal static string WeaponTypeCleaver {
            get {
                return ResourceManager.GetString("WeaponTypeCleaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string WeaponTypeClub {
            get {
                return ResourceManager.GetString("WeaponTypeClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        internal static string WeaponTypeDagger {
            get {
                return ResourceManager.GetString("WeaponTypeDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetish.
        /// </summary>
        internal static string WeaponTypeFetish {
            get {
                return ResourceManager.GetString("WeaponTypeFetish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fist.
        /// </summary>
        internal static string WeaponTypeFist {
            get {
                return ResourceManager.GetString("WeaponTypeFist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gavel.
        /// </summary>
        internal static string WeaponTypeGavel {
            get {
                return ResourceManager.GetString("WeaponTypeGavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnarled Branch.
        /// </summary>
        internal static string WeaponTypeGnarledBranch {
            get {
                return ResourceManager.GetString("WeaponTypeGnarledBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gouger.
        /// </summary>
        internal static string WeaponTypeGouger {
            get {
                return ResourceManager.GetString("WeaponTypeGouger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        internal static string WeaponTypeHammer {
            get {
                return ResourceManager.GetString("WeaponTypeHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchet.
        /// </summary>
        internal static string WeaponTypeHatchet {
            get {
                return ResourceManager.GetString("WeaponTypeHatchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horn.
        /// </summary>
        internal static string WeaponTypeHorn {
            get {
                return ResourceManager.GetString("WeaponTypeHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife.
        /// </summary>
        internal static string WeaponTypeKnife {
            get {
                return ResourceManager.GetString("WeaponTypeKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kris.
        /// </summary>
        internal static string WeaponTypeKris {
            get {
                return ResourceManager.GetString("WeaponTypeKris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labrys.
        /// </summary>
        internal static string WeaponTypeLabrys {
            get {
                return ResourceManager.GetString("WeaponTypeLabrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lathi.
        /// </summary>
        internal static string WeaponTypeLathi {
            get {
                return ResourceManager.GetString("WeaponTypeLathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mace.
        /// </summary>
        internal static string WeaponTypeMace {
            get {
                return ResourceManager.GetString("WeaponTypeMace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mallet.
        /// </summary>
        internal static string WeaponTypeMallet {
            get {
                return ResourceManager.GetString("WeaponTypeMallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maul.
        /// </summary>
        internal static string WeaponTypeMaul {
            get {
                return ResourceManager.GetString("WeaponTypeMaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paw.
        /// </summary>
        internal static string WeaponTypePaw {
            get {
                return ResourceManager.GetString("WeaponTypePaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pernarch.
        /// </summary>
        internal static string WeaponTypePernarch {
            get {
                return ResourceManager.GetString("WeaponTypePernarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piledriver.
        /// </summary>
        internal static string WeaponTypePiledriver {
            get {
                return ResourceManager.GetString("WeaponTypePiledriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poignard.
        /// </summary>
        internal static string WeaponTypePoignard {
            get {
                return ResourceManager.GetString("WeaponTypePoignard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poleaxe.
        /// </summary>
        internal static string WeaponTypePoleaxe {
            get {
                return ResourceManager.GetString("WeaponTypePoleaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterstaff.
        /// </summary>
        internal static string WeaponTypeQuarterstaff {
            get {
                return ResourceManager.GetString("WeaponTypeQuarterstaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripper.
        /// </summary>
        internal static string WeaponTypeRipper {
            get {
                return ResourceManager.GetString("WeaponTypeRipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sceptre.
        /// </summary>
        internal static string WeaponTypeSceptre {
            get {
                return ResourceManager.GetString("WeaponTypeSceptre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekhem.
        /// </summary>
        internal static string WeaponTypeSekhem {
            get {
                return ResourceManager.GetString("WeaponTypeSekhem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shank.
        /// </summary>
        internal static string WeaponTypeShank {
            get {
                return ResourceManager.GetString("WeaponTypeShank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string WeaponTypeShield {
            get {
                return ResourceManager.GetString("WeaponTypeShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skean.
        /// </summary>
        internal static string WeaponTypeSkean {
            get {
                return ResourceManager.GetString("WeaponTypeSkean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiked Bundle.
        /// </summary>
        internal static string WeaponTypeSpikedBundle {
            get {
                return ResourceManager.GetString("WeaponTypeSpikedBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter.
        /// </summary>
        internal static string WeaponTypeSplitter {
            get {
                return ResourceManager.GetString("WeaponTypeSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabber.
        /// </summary>
        internal static string WeaponTypeStabber {
            get {
                return ResourceManager.GetString("WeaponTypeStabber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string WeaponTypeStaff {
            get {
                return ResourceManager.GetString("WeaponTypeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steelhead.
        /// </summary>
        internal static string WeaponTypeSteelhead {
            get {
                return ResourceManager.GetString("WeaponTypeSteelhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiletto.
        /// </summary>
        internal static string WeaponTypeStiletto {
            get {
                return ResourceManager.GetString("WeaponTypeStiletto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenderizer.
        /// </summary>
        internal static string WeaponTypeTenderizer {
            get {
                return ResourceManager.GetString("WeaponTypeTenderizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomahawk.
        /// </summary>
        internal static string WeaponTypeTomahawk {
            get {
                return ResourceManager.GetString("WeaponTypeTomahawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wand.
        /// </summary>
        internal static string WeaponTypeWand {
            get {
                return ResourceManager.GetString("WeaponTypeWand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woodsplitter.
        /// </summary>
        internal static string WeaponTypeWoodsplitter {
            get {
                return ResourceManager.GetString("WeaponTypeWoodsplitter", resourceCulture);
            }
        }
    }
}
