//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procurement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Procurement.MessagesRes", typeof(MessagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Procurement Medved Edition is available! Would you like to download now? (Opens in browser).
        /// </summary>
        internal static string ANewVersionOfProcurementMedvedEditionIsAvailable {
            get {
                return ResourceManager.GetString("ANewVersionOfProcurementMedvedEditionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to bump your thread? By clicking yes you grant permission for Procurement to bump your forum thread using the account you logged in with, and confirm that you are only bumping within the allowed time interval as per forum rules..
        /// </summary>
        internal static string AreYouSureYouWantToBumpYourThread {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToBumpYourThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update your shop? By clicking yes you grant permission for Procurement to update your forum thread using the account you logged in with..
        /// </summary>
        internal static string AreYouSureYouWantToUpdateYourShop {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUpdateYourShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating .
        /// </summary>
        internal static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert item to text copy! Error: .
        /// </summary>
        internal static string CanTConvertItemToTextCopyError {
            get {
                return ResourceManager.GetString("CanTConvertItemToTextCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm shop update.
        /// </summary>
        internal static string ConfirmShopUpdate {
            get {
                return ResourceManager.GetString("ConfirmShopUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current leagues are:.
        /// </summary>
        internal static string CurrentLeaguesAre {
            get {
                return ResourceManager.GetString("CurrentLeaguesAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Done!.
        /// </summary>
        internal static string DoneLoading {
            get {
                return ResourceManager.GetString("DoneLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: attempted to get items for the non existant league &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorAttemptedToGetItemsForTheNonExistantLeague0 {
            get {
                return ResourceManager.GetString("ErrorAttemptedToGetItemsForTheNonExistantLeague0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error bumping shop thread, details logged to debuginfo.log.
        /// </summary>
        internal static string ErrorBumpingShopThreadDetailsLoggedToDebuginfoLog {
            get {
                return ResourceManager.GetString("ErrorBumpingShopThreadDetailsLoggedToDebuginfoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking for updates, details logged to DebugInfo.log.
        /// </summary>
        internal static string ErrorCheckingForUpdatesDetailsLoggedToDebugInfoLog {
            get {
                return ResourceManager.GetString("ErrorCheckingForUpdatesDetailsLoggedToDebugInfoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting items for {0} league, are you sure your league settings are correct?.
        /// </summary>
        internal static string ErrorGettingItemsFor0LeagueAreYouSureYourLeagueSettings {
            get {
                return ResourceManager.GetString("ErrorGettingItemsFor0LeagueAreYouSureYourLeagueSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading items.
        /// </summary>
        internal static string ErrorLoadingItems {
            get {
                return ResourceManager.GetString("ErrorLoadingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading tab preferences: .
        /// </summary>
        internal static string ErrorLoadingTabPreferences {
            get {
                return ResourceManager.GetString("ErrorLoadingTabPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in.
        /// </summary>
        internal static string ErrorLoggingIn {
            get {
                return ResourceManager.GetString("ErrorLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving image, error logged to DebugInfo.log.
        /// </summary>
        internal static string ErrorSavingImageErrorLoggedToDebugInfoLog {
            get {
                return ResourceManager.GetString("ErrorSavingImageErrorLoggedToDebugInfoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving tab preferences: .
        /// </summary>
        internal static string ErrorSavingTabPreferences {
            get {
                return ResourceManager.GetString("ErrorSavingTabPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting selected tabs: .
        /// </summary>
        internal static string ErrorSettingSelectedTabs {
            get {
                return ResourceManager.GetString("ErrorSettingSelectedTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting tabwide buyout.
        /// </summary>
        internal static string ErrorSettingTabwideBuyout {
            get {
                return ResourceManager.GetString("ErrorSettingTabwideBuyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting tabwide buyout, error details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues.
        /// </summary>
        internal static string ErrorSettingTabwideBuyoutErrorDetailsLoggedToDebugInfo {
            get {
                return ResourceManager.GetString("ErrorSettingTabwideBuyoutErrorDetailsLoggedToDebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating shop, details logged to debuginfo.log.
        /// </summary>
        internal static string ErrorUpdatingShopDetailsLoggedToDebuginfoLog {
            get {
                return ResourceManager.GetString("ErrorUpdatingShopDetailsLoggedToDebuginfoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating tab selection: .
        /// </summary>
        internal static string ErrorUpdatingTabSelection {
            get {
                return ResourceManager.GetString("ErrorUpdatingTabSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details : .
        /// </summary>
        internal static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in setTabBuyout_Click: .
        /// </summary>
        internal static string ExceptionInSetTabBuyoutClick {
            get {
                return ResourceManager.GetString("ExceptionInSetTabBuyoutClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load characters.
        /// </summary>
        internal static string FailedToLoadCharacters {
            get {
                return ResourceManager.GetString("FailedToLoadCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGG Server request limit hit, throttling activated. Please wait {0} seconds.
        /// </summary>
        internal static string GGGServerRequestLimitHitThrottlingActivated {
            get {
                return ResourceManager.GetString("GGGServerRequestLimitHitThrottlingActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image saved.
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  saved.
        /// </summary>
        internal static string ImageSaved2 {
            get {
                return ResourceManager.GetString("ImageSaved2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ThreadId!.
        /// </summary>
        internal static string InvalidThreadId {
            get {
                return ResourceManager.GetString("InvalidThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ThreadId, the ThreadId is the number at the end of the url of your shop, eg: the 12345 in http://www.pathofexile.com/forum/view-thread/12345.
        /// </summary>
        internal static string InvalidThreadIdTheThreadIdIsTheNumber {
            get {
                return ResourceManager.GetString("InvalidThreadIdTheThreadIdIsTheNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        internal static string IsRequiredPassword {
            get {
                return ResourceManager.GetString("IsRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item to text error.
        /// </summary>
        internal static string ItemToTextError {
            get {
                return ResourceManager.GetString("ItemToTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}&apos;s inventory....
        /// </summary>
        internal static string Loading0SInventory {
            get {
                return ResourceManager.GetString("Loading0SInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading characters....
        /// </summary>
        internal static string LoadingCharacters {
            get {
                return ResourceManager.GetString("LoadingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Image For .
        /// </summary>
        internal static string LoadingImageFor {
            get {
                return ResourceManager.GetString("LoadingImageFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Procurement in offline mode....
        /// </summary>
        internal static string LoadingProcurementInOfflineMode {
            get {
                return ResourceManager.GetString("LoadingProcurementInOfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading .
        /// </summary>
        internal static string LoadingStashTab1 {
            get {
                return ResourceManager.GetString("LoadingStashTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Stash Tab .
        /// </summary>
        internal static string LoadingStashTab2 {
            get {
                return ResourceManager.GetString("LoadingStashTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged as .
        /// </summary>
        internal static string LoggedAsAuth {
            get {
                return ResourceManager.GetString("LoggedAsAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings..
        /// </summary>
        internal static string NoCharactersFoundInTheLeaguesSpecified {
            get {
                return ResourceManager.GetString("NoCharactersFoundInTheLeaguesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shop settings found for current league, please configure your ThreadId and ThreadTitle under the TradeSettings tab.
        /// </summary>
        internal static string NoShopSettingsFoundForCurrentLeague {
            get {
                return ResourceManager.GetString("NoShopSettingsFoundForCurrentLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tabs selected.
        /// </summary>
        internal static string NoTabsSelected {
            get {
                return ResourceManager.GetString("NoTabsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not found!.
        /// </summary>
        internal static string SettingsNotFound {
            get {
                return ResourceManager.GetString("SettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop settings saved.
        /// </summary>
        internal static string ShopSettingsSaved {
            get {
                return ResourceManager.GetString("ShopSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop successfully updated!.
        /// </summary>
        internal static string ShopSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ShopSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop text is {0} characters, which exceeds the 50,000 character limit on the pathofexile.com forum!.
        /// </summary>
        internal static string ShopTextIs0CharactersWhichExceedsThe50000CharacterLimit {
            get {
                return ResourceManager.GetString("ShopTextIs0CharactersWhichExceedsThe50000CharacterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop thread successfully bumped!.
        /// </summary>
        internal static string ShopThreadSuccessfullyBumped {
            get {
                return ResourceManager.GetString("ShopThreadSuccessfullyBumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop updated.
        /// </summary>
        internal static string ShopUpdated {
            get {
                return ResourceManager.GetString("ShopUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread title supplied in your settings does not match the title of the thread Procurement tried to bump with the threadId in your settings. Check that your settings are correct.
        /// </summary>
        internal static string TheThreadTitleSuppliedInYourSettingsDoesNotMatch {
            get {
                return ResourceManager.GetString("TheThreadTitleSuppliedInYourSettingsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread bumped.
        /// </summary>
        internal static string ThreadBumped {
            get {
                return ResourceManager.GetString("ThreadBumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0} setting.
        ///
        ///It is either missing from settings.xml or incorrectly configured. The default setting for {0} has been loaded, but it is strongly advised that you fix your settings.xml or replace it with a default one..
        /// </summary>
        internal static string UnableToLoad0SettingItIsEitherMissingFromSettingsXml {
            get {
                return ResourceManager.GetString("UnableToLoad0SettingItIsEitherMissingFromSettingsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load setting.
        /// </summary>
        internal static string UnableToLoadSetting {
            get {
                return ResourceManager.GetString("UnableToLoadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save hover-image to disk : .
        /// </summary>
        internal static string UnableToSaveHoverImageToDisk {
            get {
                return ResourceManager.GetString("UnableToSaveHoverImageToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save shop settings, error logged to debuginfo.log.
        /// </summary>
        internal static string UnableToSaveShopSettingsErrorLoggedToDebuginfoLog {
            get {
                return ResourceManager.GetString("UnableToSaveShopSettingsErrorLoggedToDebuginfoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select at least one tab to update your shop!.
        /// </summary>
        internal static string YouNeedToSelectAtLeastOneTabToUpdateYourShop {
            get {
                return ResourceManager.GetString("YouNeedToSelectAtLeastOneTabToUpdateYourShop", resourceCulture);
            }
        }
    }
}
